### ISSUE TITLE
Proposed fixes to the code of conduct

### ISSUE THREAD

**Issue by mjugl** [PrivateAIM/.github#1]
Found a small typo in the contact section.

```diff
-If you feel uncomfortable or believe that someone has violated the code of conduct, p lease contact us at [admin@tada5hi.net](mailto:admin@tada5hi.net).
+If you feel uncomfortable or believe that someone has violated the code of conduct, please contact us at [admin@tada5hi.net](mailto:admin@tada5hi.net).
```

Also is it a good idea to have the contact address point to Peter's own domain? Any code we publish represents the project as a whole, so something like coc@privateaim.de in the future (if possible) or an address from one of the participating universities would seem more credible and "official".

**Comment by tada5hi** [comment]
Thanks for finding the typo @mjugl
No 🙈. That should actually be an email alias that represents all authors. Otherwise we could always link to you main author email address.
